# data
file_path: './data/music.mp4'
save_path: './output/music/'
mininterv: 10 # for keyframe selection
maxinterv: 30 # for keyframe selection

# diffusion
seed: 0
prompt: 'A beautiful woman with headphones listening to music in CG cyberpunk style, neon, closed eyes, colorful'
sd_path: 'stablediffusionapi/rev-animated' 
use_controlnet: True
controlnet_type: 'hed'  # 'depth', 'canny'
cond_scale: 1.0
use_freeu: False

# video-to-video translation 
batch_size: 8
num_inference_steps: 20
num_warmup_steps: 3
end_opt_step: 15
run_ebsynth: False
max_process: 4

# supporting model
gmflow_path: '/content/FRESCO/model/gmflow_sintel-0c07dcb3.pth'
sod_path: '/content/FRESCO/model/epoch_resnet.pth'
use_salinecy: True