# data
file_path: './data/car-turn.mp4'
save_path: './output/car-turn/'
mininterv: 5 # for keyframe selection
maxinterv: 5 # for keyframe selection

# diffusion
seed: 0
prompt: 'a red car turns in the winter'
# sd_path: 'runwayml/stable-diffusion-v1-5' 
# sd_path: 'stablediffusionapi/rev-animated' 
# sd_path: 'stablediffusionapi/flat-2d-animerge' 
sd_path: 'SG161222/Realistic_Vision_V2.0' 
use_controlnet: True
controlnet_type: 'hed'  # 'depth', 'canny'
cond_scale: 0.7
use_freeu: False

# video-to-video translation 
batch_size: 8
num_inference_steps: 20
num_warmup_steps: 5
end_opt_step: 15
run_ebsynth: False
max_process: 4

# supporting model
gmflow_path: '/content/FRESCO/model/gmflow_sintel-0c07dcb3.pth'
sod_path: '/content/FRESCO/model/epoch_resnet.pth'
use_salinecy: True